### ISSUE TITLE
Animation support

### ISSUE THREAD

**Issue by Grimstrikes** [LoL-Fantome/LeagueFileTranslator#1]
Thanks for the tool, works great for models. Is there a possibility to get support for animation (.anm) export/conversion as well? Description says it does have it tho, what am I missing then?

Thank you in advance!

**Comment by Crauzer** [comment]
This tool hasn't even had its first release.

Export of SKN is currently broken. Only importing of SKN files works.

I don't have any plans to support ANM files right now. I have other priorities.

The current plan is:

## LeagueFileTranslator 1.0
* SKN/SKL Import and Export
* SCB and SCO Import and Export

## LeagueFileTranslator 1.1
* Map stuff

## LeagueFileTranslator 1.2
* ANM Stuff

**Comment by Grimstrikes** [comment]
Thanks for the quick reply!

Your work and effort is extremely important/useful for game devs like me and content creators with LoL related ideas in mind, as not many other tools provide (up-to-date) access to game files like yours.

Looking forward to the releases!
