### ISSUE TITLE
I suspect that there is some data of UV animation in the anm file

### ISSUE THREAD

**Issue by rr4e** [LoL-Fantome/LeagueFileTranslator#3]
1，
Hecarim\data\characters\hecarim\skins\skin4
![Q$ZBJ6R6N1%C3Q@_7I2L) M](https://user-images.githubusercontent.com/14058293/89858970-77569700-dbd2-11ea-9c1c-1724e4709328.png)
![M4OVBLFS0A)NI3`_Z)U{P1U](https://user-images.githubusercontent.com/14058293/89858996-83daef80-dbd2-11ea-8bab-146ad867116f.png)

Hecarim\data\characters\hecarim\animationsskin4\skin4
![6BJY{EBQ}_@L 4~`$X_F%(4](https://user-images.githubusercontent.com/14058293/89859053-ad941680-dbd2-11ea-8def-958db15583ea.png)

Without modifying any code, the original look:：
![224](https://user-images.githubusercontent.com/14058293/89858851-38284600-dbd2-11ea-8779-fe4ff93f2134.gif)

2，
Hecarim\data\characters\hecarim\animationsskin4\skin4
<img width="823" alt="333" src="https://user-images.githubusercontent.com/14058293/89859246-272c0480-dbd3-11ea-9ffb-e23db7bdb1f7.png">

Only delete the result of calling anm code：
![222](https://user-images.githubusercontent.com/14058293/89858871-40808100-dbd2-11ea-9258-e96951c86e0f.gif)

**Comment by rr4e** [comment]
<img width="883" alt="Snipaste_2020-08-11_14-23-12" src="https://user-images.githubusercontent.com/14058293/89864250-395f7000-dbde-11ea-8650-c8fd5c41d7bf.png">

![666](https://user-images.githubusercontent.com/14058293/89865571-90fedb00-dbe0-11ea-85fb-1200db95f916.gif)

This should be the UV control data, but what does this have to do with anm? I used Maya2018 to export a .anm with the same frame rate and the same number of frames, but it will cause the animation to fail. Why?

When I replaced hecarim_arcade_uvtail.anm with the anm exported by my maya2018 and mounted it in the game, the tail animation failed
![123](https://user-images.githubusercontent.com/14058293/89866671-86454580-dbe2-11ea-95a6-e92c1ea45db3.gif)

**Comment by Crauzer** [comment]
You can't animate UVs with ANM files. They contain frame data only for joints.

**Comment by rr4e** [comment]
> You can't animate UVs with ANM files. They contain frame data only for joints.
So ,  what does the official hecarim\skins\skin04\animations\hecarim_arcade_uvtail.anm do ,   the "UV" tail .anm

**Comment by Crauzer** [comment]
No idea, UV animations are done through materials/particles in BIN files

**Comment by Crauzer** [comment]
The way this works is that his tail has a different material than his body. That material `(Characters/Hecarim/Skins/Skin4/Materials/Scrolling_Tail_inst)` uses the `UVScaleAndOffset` shader parameter and passes it to a shader called `Shaders/SkinnedMesh/UVOffset`

**Comment by rr4e** [comment]
> 这种工作方式是他的尾巴与身体的材质不同。该材质`(Characters/Hecarim/Skins/Skin4/Materials/Scrolling_Tail_inst)`使用`UVScaleAndOffset`shader参数并将其传递给名为`Shaders/SkinnedMesh/UVOffset`

I will continue to try and reply again if successful

**Comment by rr4e** [comment]
I will continue to try and reply again if successful

**Comment by rr4e** [comment]
> The way this works is that his tail has a different material than his body. That material `(Characters/Hecarim/Skins/Skin4/Materials/Scrolling_Tail_inst)` uses the `UVScaleAndOffset` shader parameter and passes it to a shader called `Shaders/SkinnedMesh/UVOffset`

I will continue to try and reply again if successful

**Comment by rr4e** [comment]
> The way this works is that his tail has a different material than his body. That material `(Characters/Hecarim/Skins/Skin4/Materials/Scrolling_Tail_inst)` uses the `UVScaleAndOffset` shader parameter and passes it to a shader called `Shaders/SkinnedMesh/UVOffset`

Yes，I read the bin file again，I have tried countless times before to replace the tail material (hecarim_arcade_tail) with the body material (ARCADE_HECARIM_mat), but this is just to change the texture of the body material, and there will be no rainbow flowing animation.

![2259](https://user-images.githubusercontent.com/14058293/90007359-2f686a80-dccd-11ea-8afa-f46def5b036a.gif)
![2260](https://user-images.githubusercontent.com/14058293/90007955-35128000-dcce-11ea-9514-474a2cf620ce.gif)


![2257](https://user-images.githubusercontent.com/14058293/90006398-62a9fa00-dccb-11ea-91e3-159d266c5341.gif)
